---
title: "Merging the PPT and GPF Datasets"
subtitle: "Strengthening the Dairy Value Chain"
author: "Julia Silge"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: leonids
---

```{r, echo = FALSE, warning = FALSE}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, dpi = 180)
options(width=80, dplyr.width = 150)
```

It is now time to merge the PPT and GFP datasets. Let's do it!

## Reading in Both Sets of Data

```{r}
library(readr)
gpf <- read_csv("../data/gpf_merged.csv", col_types = cols(.default = col_character()))
dim(gpf)
ppt <- read_csv("../data/ppt_merged.csv", col_types = cols(.default = col_character()))
dim(ppt)
```

Let's change the `producer_id` to numeric in both data sets so we can join by them.

```{r}
library(dplyr)
gpf <- gpf %>%
    mutate(producer_id = as.numeric(producer_id),
           round = as.numeric(round))
ppt <- ppt %>%
    mutate(producer_id = as.numeric(producer_id),
           round = as.numeric(round))
```

## Merging the Two Sets Together

Now we can merge them together using a join.

```{r}
gpf_ppt_merged <-  left_join(gpf, ppt, 
                             by = c("group_code", "round"),
                             suffix = c("_gpf", "_ppt"))
```

How big is this now?

```{r}
dim(gpf_ppt_merged)
```


## Writing the File

Let's save this as a csv.

```{r}
write_csv(gpf_ppt_merged, "../data/gpf_ppt_merged.csv")
```

